export const metadata = {
  title: 'Blogs | OTAB',
  // description: 'Generated by create next app',
}

const BlogsPage = () => {
  return (
    <div className="bg-[#131720]">

      <article className="bg-[#171f2a]">
        <h1>Name : Mahmud Priom</h1>
      </article>
     
    </div>
  );
};

export default BlogsPage;