export const metadata = {
    title: 'About | OTAB',
    // description: 'Generated by create next app',
  }
const AboutPage = () => {
    return (
        <div>
            AboutPage
        </div>
    );
};

export default AboutPage;