"use client"
import Image from "next/image";

// export const metadata = {
//     title: 'About | OTAB',
//     // description: 'Generated by create next app',
//   }
const AboutPage = () => {
    return (
        <div>
        <div className="text-center mt-5">
                <h1 className="text-4xl font-bold">ABOUT US</h1>
                <p className="text-lg my-5">A COMMERCIAL WEBSITE THAT LISTS WALLETS, EXCHANGES AND OTHER BITCOIN RELATED INFO</p>
        </div>

            <div className="grid md:grid-cols-2 grid-cols-1">
                <article>
                    <Image className='mx-auto'width={300} height={300} alt="" src='https://slimhamdi.net/bayya/images/about-us.png'></Image>
                </article>
                <article>
                    <h1 className="text-xl font-bold">WE ARE OTAB</h1>
                    <p className="my-5">A place for everyone who wants to simply buy and sell Bitcoins. Deposit funds using your Visa/MasterCard or bank transfer. Instant buy/sell of Bitcoins at fair price is guaranteed. Nothing extra. Join over 700,000 users from all over the world satisfied with our services.</p>
                </article>
            </div>
        </div>
    );
};

export default AboutPage;