export const metadata = {
    title: 'Resource | OTAB',
    // description: 'Generated by create next app',
  }
const ResourcePage = () => {
    return (
        <div>
            ResourcePage
        </div>
    );
};

export default ResourcePage;