import Navbar from '@/components/Navbar';
import React from 'react';
import Footer from '../HomePage/Footer';

export const metadata = {
    title: 'Home | OTAB',
    // description: 'Generated by create next app',
  }

const WithLayout = ({children}) => {
    return (
        <div>
            <Navbar></Navbar>
            {children}
            <Footer />
        </div>
    );
};

export default WithLayout;