import Sidebar from './Sidebar';

export const metadata = {
  title: 'Dashboard Next App',
  description: 'Generated by create next app',
}

const DashboardLayout = ({children}) => {
  return (
    <div className='flex bg-[#131720] text-slate-300 
    '>
      <div className=''>
      <Sidebar></Sidebar>
      </div>

      <div className='flex-1'>
      {children}
      </div>
    </div>
  );
};

export default DashboardLayout;