// import Sidebar from './Sidebar';

import AdminSidebar from "./adminSidebar";

export const metadata = {
  title: 'Dashboard Next App',
  description: 'Generated by create next app',
}

const AdminDashboardLayout = ({children}) => {
  return (
    <div className='flex bg-[#131720] h-full  text-slate-300 
    '>
      <div className=''>
        <AdminSidebar></AdminSidebar>

      {/* <SidebarLink></SidebarLink> */}
      </div>

      <div className='flex-1'>
      {children}
      </div>
    </div>
  );
};

export default AdminDashboardLayout;