// import Sidebar from './Sidebar';
import DashboardNav from "../dashboard/dashboardNav/dashboardNav";
import AdminSidebar from "./adminSidebar";

export const metadata = {
  title: "Dashboard Next App",
  description: "Generated by create next app",
};

const AdminDashboardLayout = ({ children }) => {
  return (
    <div
      className="flex bg-[#131720] h-full  text-slate-200 
    "
    >
      <div className="">
        <AdminSidebar></AdminSidebar>
        {/* <SidebarLink></SidebarLink> */}
      </div>

      <div className="flex-1">
        <DashboardNav></DashboardNav>
        {children}
      </div>
    </div>
  );
};

export default AdminDashboardLayout;
