import AdminHome from "@/app/adminDashboard/adminHome/page";

export const metadata = {
  title: 'adminDashboard | OTAB',
  // description: 'Generated by create next app',
}


const AdminDashboardPage = () => {

  return (
    <>
    <div>
      <AdminHome></AdminHome>
    </div>
      

    </>
  );
};

export default AdminDashboardPage;